package ec.gob.cj.pesnot.notaria.modelo;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonProperty.Access;

@Entity
@Table(name = "ACCIONPERSONAL")
public class AccionPersonal {
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long IDACCIONPERSONAL;
	
	@Column(name = "IDESTADOACCIONPERSONAL")
	private Long IDESTADOACCIONPERSONAL;
	
	@Column(name = "IDNOTARIO")
	private Long IDNOTARIO;
	
	@Column(name = "IDTIPOACCIONPERSONAL")
	private Long IDTIPOACCIONPERSONAL;
	
	@Column(name = "IDAUDITORIAACCIONPERSONAL")
	private Long IDAUDITORIAACCIONPERSONAL;

	@Column(name = "NUMEROACCIONPERSONAL")
	private Long NUMEROACCIONPERSONAL;

	@Column(name = "FECHAINICIOACCIONPERSONAL")
	private Date FECHAINICIOACCIONPERSONAL;
	
	@Column(name = "FECHAFINACCIONPERSONAL")
	private Date FECHAFINACCIONPERSONAL;
	
	@Column(name = "FECHAACCIONPERSONAL")
	private Date FECHAACCIONPERSONAL;
	
	/*@Column(name = "VIGENTEACCIONPERSONAL")
	private boolean VIGENTEACCIONPERSONAL;*/
	
	@Column(name = "OBSERVACIONACCIONPERSONAL")
	private String OBSERVACIONACCIONPERSONAL;
	
	/*@Column(name = "URLACCIONPERSONALDOC")
	private String URLACCIONPERSONALDOC;*/
	
	@Column(name = "ESTADOACTIVO")
	private boolean ESTADOACTIVO;
	
	@Column(name = "DOCUMENTOACCIONPERSONAL")
	private String DOCUMENTOACCIONPERSONAL;
	
	
	public AccionPersonal(long iDACCIONPERSONAL, long iDESTADOACCIONPERSONAL, long iDNOTARIO, long iDTIPOACCIONPERSONAL,
			long iDAUDITORIAACCIONPERSONAL, long nUMEROACCIONPERSONAL, Date fECHAINICIOACCIONPERSONAL,
			Date fECHAFINACCIONPERSONAL, Date fECHAACCIONPERSONAL, String oBSERVACIONACCIONPERSONAL,
			boolean eSTADOACTIVO, String dOCUMENTOACCIONPERSONAL) {
		super();
		IDACCIONPERSONAL = iDACCIONPERSONAL;
		IDESTADOACCIONPERSONAL = iDESTADOACCIONPERSONAL;
		IDNOTARIO = iDNOTARIO;
		IDTIPOACCIONPERSONAL = iDTIPOACCIONPERSONAL;
		IDAUDITORIAACCIONPERSONAL = iDAUDITORIAACCIONPERSONAL;
		NUMEROACCIONPERSONAL = nUMEROACCIONPERSONAL;
		FECHAINICIOACCIONPERSONAL = fECHAINICIOACCIONPERSONAL;
		FECHAFINACCIONPERSONAL = fECHAFINACCIONPERSONAL;
		FECHAACCIONPERSONAL = fECHAACCIONPERSONAL;
		OBSERVACIONACCIONPERSONAL = oBSERVACIONACCIONPERSONAL;
		ESTADOACTIVO = eSTADOACTIVO;
		DOCUMENTOACCIONPERSONAL = dOCUMENTOACCIONPERSONAL;
	}
	
	

	public AccionPersonal() {
		super();
	}



	public Long getIDACCIONPERSONAL() {
		return IDACCIONPERSONAL;
	}

	public void setIDACCIONPERSONAL(Long iDACCIONPERSONAL) {
		IDACCIONPERSONAL = iDACCIONPERSONAL;
	}

	public Long getNUMEROACCIONPERSONAL() {
		return NUMEROACCIONPERSONAL;
	}

	public void setNUMEROACCIONPERSONAL(Long nUMEROACCIONPERSONAL) {
		NUMEROACCIONPERSONAL = nUMEROACCIONPERSONAL;
	}

	public Date getFECHAINICIOACCIONPERSONAL() {
		return FECHAINICIOACCIONPERSONAL;
	}

	public void setFECHAINICIOACCIONPERSONAL(Date fECHAINICIOACCIONPERSONAL) {
		FECHAINICIOACCIONPERSONAL = fECHAINICIOACCIONPERSONAL;
	}

	public Date getFECHAFINACCIONPERSONAL() {
		return FECHAFINACCIONPERSONAL;
	}

	public void setFECHAFINACCIONPERSONAL(Date fECHAFINACCIONPERSONAL) {
		FECHAFINACCIONPERSONAL = fECHAFINACCIONPERSONAL;
	}

	public Date getFECHAACCIONPERSONAL() {
		return FECHAACCIONPERSONAL;
	}

	public void setFECHAACCIONPERSONAL(Date fECHAACCIONPERSONAL) {
		FECHAACCIONPERSONAL = fECHAACCIONPERSONAL;
	}


	public String getOBSERVACIONACCIONPERSONAL() {
		return OBSERVACIONACCIONPERSONAL;
	}

	public void setOBSERVACIONACCIONPERSONAL(String oBSERVACIONACCIONPERSONAL) {
		OBSERVACIONACCIONPERSONAL = oBSERVACIONACCIONPERSONAL;
	}
	
	public boolean isESTADOACTIVO() {
		return ESTADOACTIVO;
	}

	public void setESTADOACTIVO(boolean eSTADOACTIVO) {
		ESTADOACTIVO = eSTADOACTIVO;
	}

	public String getDOCUMENTOACCIONPERSONAL() {
		return DOCUMENTOACCIONPERSONAL;
	}

	public void setDOCUMENTOACCIONPERSONAL(String dOCUMENTOACCIONPERSONAL) {
		DOCUMENTOACCIONPERSONAL = dOCUMENTOACCIONPERSONAL;
	}

	public Long getIDESTADOACCIONPERSONAL() {
		return IDESTADOACCIONPERSONAL;
	}

	public void setIDESTADOACCIONPERSONAL(Long iDESTADOACCIONPERSONAL) {
		IDESTADOACCIONPERSONAL = iDESTADOACCIONPERSONAL;
	}

	public Long getIDNOTARIO() {
		return IDNOTARIO;
	}

	public void setIDNOTARIO(Long iDNOTARIO) {
		IDNOTARIO = iDNOTARIO;
	}

	public Long getIDTIPOACCIONPERSONAL() {
		return IDTIPOACCIONPERSONAL;
	}

	public void setIDTIPOACCIONPERSONAL(Long iDTIPOACCIONPERSONAL) {
		IDTIPOACCIONPERSONAL = iDTIPOACCIONPERSONAL;
	}

	public Long getIDAUDITORIAACCIONPERSONAL() {
		return IDAUDITORIAACCIONPERSONAL;
	}

	public void setIDAUDITORIAACCIONPERSONAL(Long iDAUDITORIAACCIONPERSONAL) {
		IDAUDITORIAACCIONPERSONAL = iDAUDITORIAACCIONPERSONAL;
	}
	
	
	
	
	
	
	
	
	
	
	
	
	
}
